"""empty message

Revision ID: 16133cb5ec49
Revises: 5229af235c02
Create Date: 2025-10-20 20:02:07.941813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16133cb5ec49'
down_revision = '5229af235c02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('url', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('description', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.drop_column('description')
        batch_op.drop_column('url')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
