"""empty message

Revision ID: 48402d37a231
Revises: a42c0e0a5e99
Create Date: 2025-10-17 19:43:27.087249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48402d37a231'
down_revision = 'a42c0e0a5e99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
