"""Add image_header field to course and blog models

Revision ID: 52a06fab86a6
Revises: 6feac45175b8
Create Date: 2025-11-11 14:28:01.220802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52a06fab86a6'
down_revision = '6feac45175b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_header', sa.String(length=255), nullable=True))

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_header', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('image_header')

    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.drop_column('image_header')

    # ### end Alembic commands ###
