"""Add indexes to purchase user_id and course_id columns

Revision ID: 54a8914b84e9
Revises: ce6acb7f4143
Create Date: 2025-11-13 20:32:31.841079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54a8914b84e9'
down_revision = 'ce6acb7f4143'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article')
    op.drop_table('shop')
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchases_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchases_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchases_user_id'))
        batch_op.drop_index(batch_op.f('ix_purchases_course_id'))

    op.create_table('shop',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('article', sa.VARCHAR(length=100), nullable=False),
    sa.Column('price', sa.NUMERIC(precision=4, scale=2), nullable=False),
    sa.Column('date', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('total_price', sa.NUMERIC(precision=4, scale=2), nullable=False),
    sa.Column('method_payment', sa.VARCHAR(length=100), nullable=False),
    sa.Column('status', sa.VARCHAR(length=100), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('article',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('shop_id', sa.INTEGER(), nullable=False),
    sa.Column('course_id', sa.INTEGER(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('price', sa.NUMERIC(precision=4, scale=2), nullable=False),
    sa.Column('subtotal', sa.NUMERIC(precision=4, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shop.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
