"""empty message

Revision ID: cb02a8d85246
Revises: 0fd360cb8891
Create Date: 2025-10-20 20:46:14.756030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb02a8d85246'
down_revision = '0fd360cb8891'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.create_unique_constraint('course_name', ['name'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint('user_email', ['email'])
        batch_op.create_unique_constraint('username', ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('username', type_='unique')
        batch_op.drop_constraint('user_email', type_='unique')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint('course_name', type_='unique')

    op.create_table('products',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('price', sa.NUMERIC(precision=4, scale=2), nullable=False),
    sa.Column('discount', sa.NUMERIC(precision=4, scale=2), nullable=False),
    sa.Column('language', sa.VARCHAR(length=100), nullable=False),
    sa.Column('topic', sa.VARCHAR(length=100), nullable=False),
    sa.Column('level', sa.VARCHAR(length=100), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
